/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visao;

import br.com.visao.telas.Atualiza;
import br.com.visao.telas.Cadastros;
import br.com.visao.telas.Exclui;
import br.com.visao.telas.Movimentos;
import br.com.visao.telas.Relatorio;
import br.com.visao.telas.Temas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.Timer;

/**
 *
 * @author Rafael Paes Leme - Programador Principal
 */
public class Principal extends javax.swing.JFrame {

    private static Principal p;

    public static Principal getInstancia() {

        if (p == null) {

            p = new Principal();

        }

        return p;

    }


    public static JDesktopPane getPainel() {

        return getInstancia().DesktopPane;

    }

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_fechar = new javax.swing.JLabel();
        bt_minimizar1 = new javax.swing.JPanel();
        bt_minimizar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        config = new javax.swing.JLabel();
        sobre = new javax.swing.JLabel();
        msg_usuario = new javax.swing.JLabel();
        msg_ola = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        altera_tema = new javax.swing.JLabel();
        logoff = new javax.swing.JLabel();
        bd = new javax.swing.JLabel();
        licenca = new javax.swing.JLabel();
        sair = new javax.swing.JLabel();
        bt_cadastrar = new javax.swing.JButton();
        bt_movimento = new javax.swing.JButton();
        bt_atualiza = new javax.swing.JButton();
        bt_exclui = new javax.swing.JButton();
        bt_relatorios = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        JLDATA = new javax.swing.JLabel();
        JLHORA = new javax.swing.JLabel();
        DesktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        bt_fechar.setFont(new java.awt.Font("Khmer UI", 0, 30)); // NOI18N
        bt_fechar.setForeground(new java.awt.Color(255, 255, 255));
        bt_fechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_fechar.setText("X");
        bt_fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_fecharMousePressed(evt);
            }
        });

        bt_minimizar1.setBackground(new java.awt.Color(0, 102, 153));
        bt_minimizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_minimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_minimizar1MousePressed(evt);
            }
        });

        bt_minimizar.setBackground(new java.awt.Color(0, 102, 153));
        bt_minimizar.setFont(new java.awt.Font("Khmer UI", 1, 30)); // NOI18N
        bt_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        bt_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_minimizar.setText("-");
        bt_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_minimizar.setOpaque(true);
        bt_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_minimizarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout bt_minimizar1Layout = new javax.swing.GroupLayout(bt_minimizar1);
        bt_minimizar1.setLayout(bt_minimizar1Layout);
        bt_minimizar1Layout.setHorizontalGroup(
            bt_minimizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_minimizar1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(bt_minimizar)
                .addContainerGap())
        );
        bt_minimizar1Layout.setVerticalGroup(
            bt_minimizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_minimizar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imagem/goel_teste.PNG"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        config.setFont(new java.awt.Font("Khmer UI", 0, 14)); // NOI18N
        config.setForeground(new java.awt.Color(255, 255, 255));
        config.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        config.setText("Configurações");
        config.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        config.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                configMouseDragged(evt);
            }
        });
        config.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                configMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                configMouseReleased(evt);
            }
        });

        sobre.setFont(new java.awt.Font("Khmer UI", 0, 14)); // NOI18N
        sobre.setForeground(new java.awt.Color(255, 255, 255));
        sobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sobre.setText("Sobre");
        sobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sobreMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sobreMousePressed(evt);
            }
        });

        msg_usuario.setFont(new java.awt.Font("Khmer UI", 0, 14)); // NOI18N
        msg_usuario.setForeground(new java.awt.Color(255, 255, 255));
        msg_usuario.setText("Usuario");

        msg_ola.setFont(new java.awt.Font("Khmer UI", 0, 14)); // NOI18N
        msg_ola.setForeground(new java.awt.Color(255, 255, 255));
        msg_ola.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        msg_ola.setText("Olá!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(config)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sobre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 576, Short.MAX_VALUE)
                .addComponent(msg_ola, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(msg_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_minimizar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_fechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_minimizar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(msg_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(msg_ola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setVisible(false);
        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jLabel15.setBackground(new java.awt.Color(0, 153, 153));
        jLabel15.setFont(new java.awt.Font("Khmer UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Direitos Reservados");
        jLabel15.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(0, 153, 153));
        jLabel16.setFont(new java.awt.Font("Khmer UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Goel");
        jLabel16.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(0, 153, 153));
        jLabel17.setFont(new java.awt.Font("Khmer UI", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Tecnologia");
        jLabel17.setOpaque(true);

        jLabel18.setBackground(new java.awt.Color(0, 153, 153));
        jLabel18.setFont(new java.awt.Font("Khmer UI", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Desenvolvido por:");
        jLabel18.setOpaque(true);

        jLabel19.setBackground(new java.awt.Color(0, 153, 153));
        jLabel19.setFont(new java.awt.Font("Khmer UI", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Rafael S. Paes Leme");
        jLabel19.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jPanel5.setVisible(false);
        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        altera_tema.setBackground(new java.awt.Color(0, 102, 153));
        altera_tema.setFont(new java.awt.Font("Khmer UI", 0, 12)); // NOI18N
        altera_tema.setForeground(new java.awt.Color(255, 255, 255));
        altera_tema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        altera_tema.setText("Alterar Tema");
        altera_tema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        altera_tema.setOpaque(true);
        altera_tema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                altera_temaMousePressed(evt);
            }
        });

        logoff.setBackground(new java.awt.Color(0, 102, 153));
        logoff.setFont(new java.awt.Font("Khmer UI", 0, 12)); // NOI18N
        logoff.setForeground(new java.awt.Color(255, 255, 255));
        logoff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoff.setText("Logoff");
        logoff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoff.setOpaque(true);

        bd.setBackground(new java.awt.Color(0, 102, 153));
        bd.setFont(new java.awt.Font("Khmer UI", 0, 12)); // NOI18N
        bd.setForeground(new java.awt.Color(255, 255, 255));
        bd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bd.setText("Banco de Dados");
        bd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bd.setEnabled(false);
        bd.setOpaque(true);

        licenca.setBackground(new java.awt.Color(0, 102, 153));
        licenca.setFont(new java.awt.Font("Khmer UI", 0, 12)); // NOI18N
        licenca.setForeground(new java.awt.Color(255, 255, 255));
        licenca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        licenca.setText("Licença");
        licenca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        licenca.setOpaque(true);

        sair.setBackground(new java.awt.Color(0, 102, 153));
        sair.setFont(new java.awt.Font("Khmer UI", 0, 12)); // NOI18N
        sair.setForeground(new java.awt.Color(255, 255, 255));
        sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sair.setText("Sair");
        sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sair.setOpaque(true);
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sairMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(altera_tema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bd, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(licenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(altera_tema, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoff, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(licenca, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 150));

        bt_cadastrar.setBackground(new java.awt.Color(204, 204, 255));
        bt_cadastrar.setFont(new java.awt.Font("Khmer UI", 1, 18)); // NOI18N
        bt_cadastrar.setForeground(new java.awt.Color(0, 51, 153));
        bt_cadastrar.setText("CADASTRO");
        bt_cadastrar.setActionCommand("");
        bt_cadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_cadastrar.setContentAreaFilled(false);
        bt_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_cadastrarMousePressed(evt);
            }
        });
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 90));

        bt_movimento.setBackground(new java.awt.Color(204, 204, 255));
        bt_movimento.setFont(new java.awt.Font("Khmer UI", 1, 18)); // NOI18N
        bt_movimento.setForeground(new java.awt.Color(0, 51, 153));
        bt_movimento.setText("MOVIMENTO");
        bt_movimento.setActionCommand("");
        bt_movimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_movimento.setContentAreaFilled(false);
        bt_movimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_movimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_movimentoMousePressed(evt);
            }
        });
        bt_movimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_movimentoActionPerformed(evt);
            }
        });
        jPanel2.add(bt_movimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 134, 250, 90));

        bt_atualiza.setBackground(new java.awt.Color(204, 204, 255));
        bt_atualiza.setFont(new java.awt.Font("Khmer UI", 1, 18)); // NOI18N
        bt_atualiza.setForeground(new java.awt.Color(0, 51, 153));
        bt_atualiza.setText("ATUALIZAÇÕES");
        bt_atualiza.setActionCommand("");
        bt_atualiza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_atualiza.setContentAreaFilled(false);
        bt_atualiza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_atualiza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_atualizaMousePressed(evt);
            }
        });
        bt_atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizaActionPerformed(evt);
            }
        });
        jPanel2.add(bt_atualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 90));

        bt_exclui.setBackground(new java.awt.Color(204, 204, 255));
        bt_exclui.setFont(new java.awt.Font("Khmer UI", 1, 18)); // NOI18N
        bt_exclui.setForeground(new java.awt.Color(0, 51, 153));
        bt_exclui.setText("EXCLUSÕES");
        bt_exclui.setActionCommand("");
        bt_exclui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_exclui.setContentAreaFilled(false);
        bt_exclui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_exclui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_excluiMousePressed(evt);
            }
        });
        bt_exclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluiActionPerformed(evt);
            }
        });
        jPanel2.add(bt_exclui, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 326, 250, 90));

        bt_relatorios.setBackground(new java.awt.Color(204, 204, 255));
        bt_relatorios.setFont(new java.awt.Font("Khmer UI", 1, 18)); // NOI18N
        bt_relatorios.setForeground(new java.awt.Color(0, 51, 153));
        bt_relatorios.setText("RELATORIOS");
        bt_relatorios.setActionCommand("");
        bt_relatorios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_relatorios.setContentAreaFilled(false);
        bt_relatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_relatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_relatoriosMousePressed(evt);
            }
        });
        bt_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_relatoriosActionPerformed(evt);
            }
        });
        jPanel2.add(bt_relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 422, 250, 90));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        JLDATA.setBackground(new java.awt.Color(0, 102, 153));
        JLDATA.setFont(new java.awt.Font("Khmer UI", 0, 11)); // NOI18N
        JLDATA.setForeground(new java.awt.Color(255, 255, 102));
        JLDATA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLDATA.setText("00/00/0000");
        JLDATA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        JLDATA.setOpaque(true);

        JLHORA.setBackground(new java.awt.Color(0, 102, 153));
        JLHORA.setFont(new java.awt.Font("Khmer UI", 0, 11)); // NOI18N
        JLHORA.setForeground(new java.awt.Color(255, 255, 102));
        JLHORA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLHORA.setText("00:00:00");
        JLHORA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        JLHORA.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLDATA, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLHORA, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLDATA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLHORA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 230, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 570));

        DesktopPane.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);
        DesktopPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DesktopPaneMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(DesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 820, 520));

        setSize(new java.awt.Dimension(1088, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_fecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_fecharMousePressed

        System.exit(WIDTH);

        // TODO add your handling code here:
    }//GEN-LAST:event_bt_fecharMousePressed

    private void bt_minimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_minimizarMousePressed

        jPanel6.setVisible(false);
        jPanel5.setVisible(false);
        setExtendedState(ICONIFIED);

        // TODO add your handling code here:
    }//GEN-LAST:event_bt_minimizarMousePressed

    private void bt_minimizar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_minimizar1MousePressed

        jPanel6.setVisible(false);
        jPanel5.setVisible(false);
        setExtendedState(ICONIFIED);

        // TODO add your handling code here:
    }//GEN-LAST:event_bt_minimizar1MousePressed

    private void configMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseDragged

        // TODO add your handling code here:
    }//GEN-LAST:event_configMouseDragged

    private void configMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_configMouseClicked

    private void configMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseEntered

        jPanel5.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_configMouseEntered

    private void configMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseExited

        // TODO add your handling code here:
    }//GEN-LAST:event_configMouseExited

    private void configMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMousePressed

        jPanel5.setVisible(true);
        jPanel6.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_configMousePressed

    private void configMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_configMouseReleased

    private void sobreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreMouseEntered

        jPanel6.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_sobreMouseEntered

    private void sobreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreMousePressed

        jPanel6.setVisible(true);
        jPanel5.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_sobreMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

        jPanel6.setVisible(false);
        jPanel5.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void sairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMousePressed

        System.exit(WIDTH);

        // TODO add your handling code here:
    }//GEN-LAST:event_sairMousePressed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

        jPanel6.setVisible(false);
        jPanel5.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed

    private void bt_cadastrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cadastrarMousePressed

        jPanel6.setVisible(false);
        jPanel5.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cadastrarMousePressed

    private void bt_movimentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_movimentoMousePressed

        jPanel6.setVisible(false);
        jPanel5.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_bt_movimentoMousePressed

    private void bt_atualizaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_atualizaMousePressed

        jPanel6.setVisible(false);
        jPanel5.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_bt_atualizaMousePressed

    private void bt_excluiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_excluiMousePressed

        jPanel6.setVisible(false);
        jPanel5.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_bt_excluiMousePressed

    private void bt_relatoriosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_relatoriosMousePressed

        jPanel6.setVisible(false);
        jPanel5.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_bt_relatoriosMousePressed

    private void DesktopPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesktopPaneMousePressed

        jPanel6.setVisible(false);
        jPanel5.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_DesktopPaneMousePressed

    private void bt_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_relatoriosActionPerformed

        Relatorio exiberelatorio = new Relatorio();
        chamarTelas(exiberelatorio);

// TODO add your handling code here:
    }//GEN-LAST:event_bt_relatoriosActionPerformed

    private void altera_temaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altera_temaMousePressed

        Temas exibetema = new Temas();
        chamarTelas(exibetema);

// TODO add your handling code here:
    }//GEN-LAST:event_altera_temaMousePressed

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed

        Cadastros exibecadastro = new Cadastros();
        chamarTelas(exibecadastro);

// TODO add your handling code here:
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    private void bt_movimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_movimentoActionPerformed

        Movimentos exibemovimentos = new Movimentos();
        chamarTelas(exibemovimentos);

// TODO add your handling code here:
    }//GEN-LAST:event_bt_movimentoActionPerformed

    private void bt_atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizaActionPerformed

        Atualiza exibeatualiza = new Atualiza();
        chamarTelas(exibeatualiza);

// TODO add your handling code here:
    }//GEN-LAST:event_bt_atualizaActionPerformed

    private void bt_excluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluiActionPerformed

        Exclui exibeexclui = new Exclui();
        chamarTelas(exibeexclui);

// TODO add your handling code here:
    }//GEN-LAST:event_bt_excluiActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        JLDATA.setText(formato.format(dataSistema));
        
        Timer timer = new Timer(1000, new hora());
        timer.start();
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                getInstancia().setVisible(true);
            }
        });

    }

    public void chamarTelas(JInternalFrame p) {

        DesktopPane.add(p);
//Width = largura
//height = altura
        int x = (DesktopPane.getWidth() / 2) - (p.getWidth() / 2);
        int y = (DesktopPane.getHeight() / 2) - (p.getHeight() / 2);
        p.setVisible(true);
        p.setLocation(x, y);
        p.toFront();
        p.show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel JLDATA;
    private javax.swing.JLabel JLHORA;
    private javax.swing.JLabel altera_tema;
    private javax.swing.JLabel bd;
    private javax.swing.JButton bt_atualiza;
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_exclui;
    private javax.swing.JLabel bt_fechar;
    private javax.swing.JLabel bt_minimizar;
    private javax.swing.JPanel bt_minimizar1;
    private javax.swing.JButton bt_movimento;
    private javax.swing.JButton bt_relatorios;
    private javax.swing.JLabel config;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel licenca;
    private javax.swing.JLabel logoff;
    private javax.swing.JLabel msg_ola;
    private javax.swing.JLabel msg_usuario;
    private javax.swing.JLabel sair;
    private javax.swing.JLabel sobre;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener {
        
        @Override
        public void actionPerformed (ActionEvent e) {
            
            Calendar now = Calendar.getInstance();
            
      JLHORA.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
        
    }


}
