/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visao.telas.cadastro;

import br.com.visao.Principal;
import br.com.visao.telas.Cadastros;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rafael Paes Leme
 */
public class contas extends javax.swing.JInternalFrame {

    /**
     * Creates new form contas
     */
    public contas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_a_receber = new javax.swing.JButton();
        bt_a_pagar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Contas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bt_a_receber.setBackground(new java.awt.Color(0, 102, 255));
        bt_a_receber.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_a_receber.setForeground(new java.awt.Color(255, 255, 255));
        bt_a_receber.setText("A RECEBER");
        bt_a_receber.setBorderPainted(false);
        bt_a_receber.setContentAreaFilled(false);
        bt_a_receber.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_a_receber.setOpaque(true);
        bt_a_receber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_a_receberActionPerformed(evt);
            }
        });

        bt_a_pagar.setBackground(new java.awt.Color(51, 102, 255));
        bt_a_pagar.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_a_pagar.setForeground(new java.awt.Color(255, 255, 255));
        bt_a_pagar.setText("A PAGAR");
        bt_a_pagar.setBorderPainted(false);
        bt_a_pagar.setContentAreaFilled(false);
        bt_a_pagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_a_pagar.setOpaque(true);
        bt_a_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_a_pagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_a_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_a_receber, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_a_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_a_receber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_a_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_a_pagarActionPerformed

        a_pagar exibea_pagar = new a_pagar();
        Principal.getPainel().add(exibea_pagar);
        exibea_pagar.setVisible(true);

        int x = (Principal.getPainel().getWidth() / 2) - (exibea_pagar.getWidth() / 2);
        int y = (Principal.getPainel().getHeight() / 2) - (exibea_pagar.getHeight() / 2);
        exibea_pagar.setVisible(true);
        exibea_pagar.setLocation(x, y);
        exibea_pagar.toFront();
        exibea_pagar.show();

        //Codigo para fechar janelinha após clique!!!
        try {
            setClosed(iconable);

// TODO add your handling code here:
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Cadastros.class.getName()).log(Level.SEVERE, null, ex);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_bt_a_pagarActionPerformed

    private void bt_a_receberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_a_receberActionPerformed

        a_receber exibea_receber = new a_receber();
        Principal.getPainel().add(exibea_receber);
        exibea_receber.setVisible(true);

        int x = (Principal.getPainel().getWidth() / 2) - (exibea_receber.getWidth() / 2);
        int y = (Principal.getPainel().getHeight() / 2) - (exibea_receber.getHeight() / 2);
        exibea_receber.setVisible(true);
        exibea_receber.setLocation(x, y);
        exibea_receber.toFront();
        exibea_receber.show();

        //Codigo para fechar janelinha após clique!!!
        try {
            setClosed(iconable);

// TODO add your handling code here:
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Cadastros.class.getName()).log(Level.SEVERE, null, ex);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_bt_a_receberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_a_pagar;
    private javax.swing.JButton bt_a_receber;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
