/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visao.telas;

import br.com.visao.Principal;
import br.com.visao.telas.atualiza.clientes;
import br.com.visao.telas.atualiza.colaboradores;
import br.com.visao.telas.atualiza.contas;
import br.com.visao.telas.atualiza.contatos;
import br.com.visao.telas.atualiza.fornecedores;
import br.com.visao.telas.atualiza.produtos;
import br.com.visao.telas.atualiza.vendas_e_servicos;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Rafael Paes Leme
 */
public class Atualiza extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastros
     */
    public Atualiza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_cliente_atualiza = new javax.swing.JButton();
        bt_fornecedor_atualiza = new javax.swing.JButton();
        bt_produto_atualiza = new javax.swing.JButton();
        bt_vs_atualiza = new javax.swing.JButton();
        bt_contas_atualiza = new javax.swing.JButton();
        bt_contato_atualiza = new javax.swing.JButton();
        bt_colaboradores_atualiza = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Opções de Atualizações");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bt_cliente_atualiza.setBackground(new java.awt.Color(153, 153, 255));
        bt_cliente_atualiza.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_cliente_atualiza.setForeground(new java.awt.Color(255, 255, 255));
        bt_cliente_atualiza.setText("CLIENTES");
        bt_cliente_atualiza.setActionCommand("");
        bt_cliente_atualiza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_cliente_atualiza.setBorderPainted(false);
        bt_cliente_atualiza.setContentAreaFilled(false);
        bt_cliente_atualiza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_cliente_atualiza.setOpaque(true);
        bt_cliente_atualiza.setRequestFocusEnabled(false);
        bt_cliente_atualiza.setRolloverEnabled(false);
        bt_cliente_atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cliente_atualizaActionPerformed(evt);
            }
        });

        bt_fornecedor_atualiza.setBackground(new java.awt.Color(153, 153, 255));
        bt_fornecedor_atualiza.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_fornecedor_atualiza.setForeground(new java.awt.Color(255, 255, 255));
        bt_fornecedor_atualiza.setText("FORNECEDORES");
        bt_fornecedor_atualiza.setActionCommand("");
        bt_fornecedor_atualiza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_fornecedor_atualiza.setBorderPainted(false);
        bt_fornecedor_atualiza.setContentAreaFilled(false);
        bt_fornecedor_atualiza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_fornecedor_atualiza.setOpaque(true);
        bt_fornecedor_atualiza.setRequestFocusEnabled(false);
        bt_fornecedor_atualiza.setRolloverEnabled(false);
        bt_fornecedor_atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fornecedor_atualizaActionPerformed(evt);
            }
        });

        bt_produto_atualiza.setBackground(new java.awt.Color(153, 153, 255));
        bt_produto_atualiza.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_produto_atualiza.setForeground(new java.awt.Color(255, 255, 255));
        bt_produto_atualiza.setText("PRODUTOS");
        bt_produto_atualiza.setActionCommand("");
        bt_produto_atualiza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_produto_atualiza.setBorderPainted(false);
        bt_produto_atualiza.setContentAreaFilled(false);
        bt_produto_atualiza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_produto_atualiza.setOpaque(true);
        bt_produto_atualiza.setRequestFocusEnabled(false);
        bt_produto_atualiza.setRolloverEnabled(false);
        bt_produto_atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_produto_atualizaActionPerformed(evt);
            }
        });

        bt_vs_atualiza.setBackground(new java.awt.Color(153, 153, 255));
        bt_vs_atualiza.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_vs_atualiza.setForeground(new java.awt.Color(255, 255, 255));
        bt_vs_atualiza.setText("VENDAS E SERVIÇOS");
        bt_vs_atualiza.setActionCommand("");
        bt_vs_atualiza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_vs_atualiza.setBorderPainted(false);
        bt_vs_atualiza.setContentAreaFilled(false);
        bt_vs_atualiza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_vs_atualiza.setOpaque(true);
        bt_vs_atualiza.setRequestFocusEnabled(false);
        bt_vs_atualiza.setRolloverEnabled(false);
        bt_vs_atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_vs_atualizaActionPerformed(evt);
            }
        });

        bt_contas_atualiza.setBackground(new java.awt.Color(153, 153, 255));
        bt_contas_atualiza.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_contas_atualiza.setForeground(new java.awt.Color(255, 255, 255));
        bt_contas_atualiza.setText("CONTAS");
        bt_contas_atualiza.setActionCommand("");
        bt_contas_atualiza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_contas_atualiza.setBorderPainted(false);
        bt_contas_atualiza.setContentAreaFilled(false);
        bt_contas_atualiza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_contas_atualiza.setOpaque(true);
        bt_contas_atualiza.setRequestFocusEnabled(false);
        bt_contas_atualiza.setRolloverEnabled(false);
        bt_contas_atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_contas_atualizaActionPerformed(evt);
            }
        });

        bt_contato_atualiza.setBackground(new java.awt.Color(153, 153, 255));
        bt_contato_atualiza.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_contato_atualiza.setForeground(new java.awt.Color(255, 255, 255));
        bt_contato_atualiza.setText("CONTATO");
        bt_contato_atualiza.setActionCommand("");
        bt_contato_atualiza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_contato_atualiza.setBorderPainted(false);
        bt_contato_atualiza.setContentAreaFilled(false);
        bt_contato_atualiza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_contato_atualiza.setOpaque(true);
        bt_contato_atualiza.setRequestFocusEnabled(false);
        bt_contato_atualiza.setRolloverEnabled(false);
        bt_contato_atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_contato_atualizaActionPerformed(evt);
            }
        });

        bt_colaboradores_atualiza.setBackground(new java.awt.Color(153, 153, 255));
        bt_colaboradores_atualiza.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_colaboradores_atualiza.setForeground(new java.awt.Color(255, 255, 255));
        bt_colaboradores_atualiza.setText("COLABORADORES");
        bt_colaboradores_atualiza.setActionCommand("");
        bt_colaboradores_atualiza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_colaboradores_atualiza.setBorderPainted(false);
        bt_colaboradores_atualiza.setContentAreaFilled(false);
        bt_colaboradores_atualiza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_colaboradores_atualiza.setOpaque(true);
        bt_colaboradores_atualiza.setRequestFocusEnabled(false);
        bt_colaboradores_atualiza.setRolloverEnabled(false);
        bt_colaboradores_atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_colaboradores_atualizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_cliente_atualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_fornecedor_atualiza, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
            .addComponent(bt_produto_atualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_vs_atualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_contas_atualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_contato_atualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_colaboradores_atualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cliente_atualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_fornecedor_atualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_produto_atualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_vs_atualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_contas_atualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_contato_atualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_colaboradores_atualiza, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cliente_atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cliente_atualizaActionPerformed

        clientes exibecliente = new clientes();
        chamarTelas(exibecliente);

        //Codigo para fechar janelinha após clique!!!
        try {
            setClosed(iconable);

// TODO add your handling code here:
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Cadastros.class.getName()).log(Level.SEVERE, null, ex);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_bt_cliente_atualizaActionPerformed

    private void bt_fornecedor_atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fornecedor_atualizaActionPerformed

        fornecedores exibefornecedores = new fornecedores();
        chamarTelas(exibefornecedores);

        //Codigo para fechar janelinha após clique!!!
        try {
            setClosed(iconable);

// TODO add your handling code here:
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Cadastros.class.getName()).log(Level.SEVERE, null, ex);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_bt_fornecedor_atualizaActionPerformed

    private void bt_produto_atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_produto_atualizaActionPerformed

        produtos exibeprodutos = new produtos();
        chamarTelas(exibeprodutos);

        //Codigo para fechar janelinha após clique!!!
        try {
            setClosed(iconable);

// TODO add your handling code here:
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Cadastros.class.getName()).log(Level.SEVERE, null, ex);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_bt_produto_atualizaActionPerformed

    private void bt_vs_atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_vs_atualizaActionPerformed

        vendas_e_servicos exibeves = new vendas_e_servicos();
        chamarTelas(exibeves);

        //Codigo para fechar janelinha após clique!!!
        try {
            setClosed(iconable);

// TODO add your handling code here:
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Cadastros.class.getName()).log(Level.SEVERE, null, ex);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_bt_vs_atualizaActionPerformed

    private void bt_contas_atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_contas_atualizaActionPerformed

        contas c = new contas();
        chamarTelas(c);
        
        this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_bt_contas_atualizaActionPerformed

    private void bt_contato_atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_contato_atualizaActionPerformed

        contatos ct = new contatos();
        chamarTelas(ct);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bt_contato_atualizaActionPerformed

    private void bt_colaboradores_atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_colaboradores_atualizaActionPerformed

        colaboradores clb = new colaboradores();
        chamarTelas(clb);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bt_colaboradores_atualizaActionPerformed

    private void chamarTelas(JInternalFrame p) {

        Principal.getPainel().add(p);
        p.setVisible(true);

        int x = (Principal.getPainel().getWidth() / 2) - (p.getWidth() / 2);
        int y = (Principal.getPainel().getHeight() / 2) - (p.getHeight() / 2);
        p.setVisible(true);
        p.setLocation(x, y);
        p.toFront();
        p.show();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cliente_atualiza;
    private javax.swing.JButton bt_colaboradores_atualiza;
    private javax.swing.JButton bt_contas_atualiza;
    private javax.swing.JButton bt_contato_atualiza;
    private javax.swing.JButton bt_fornecedor_atualiza;
    private javax.swing.JButton bt_produto_atualiza;
    private javax.swing.JButton bt_vs_atualiza;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
