/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visao.telas;

/**
 *
 * @author Rafael Paes Leme
 */
public class Exclui extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastros
     */
    public Exclui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_cliente_exclui = new javax.swing.JButton();
        bt_fornecedor_exclui = new javax.swing.JButton();
        bt_produto_exclui = new javax.swing.JButton();
        bt_vs_exclui = new javax.swing.JButton();
        bt_conta_exclui = new javax.swing.JButton();
        bt_contato_exclui = new javax.swing.JButton();
        bt_colaborador_exclui = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Opções de Exclusão");
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bt_cliente_exclui.setBackground(new java.awt.Color(153, 153, 255));
        bt_cliente_exclui.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_cliente_exclui.setForeground(new java.awt.Color(255, 255, 255));
        bt_cliente_exclui.setText("CLIENTES");
        bt_cliente_exclui.setActionCommand("");
        bt_cliente_exclui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_cliente_exclui.setBorderPainted(false);
        bt_cliente_exclui.setContentAreaFilled(false);
        bt_cliente_exclui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_cliente_exclui.setOpaque(true);
        bt_cliente_exclui.setRequestFocusEnabled(false);
        bt_cliente_exclui.setRolloverEnabled(false);

        bt_fornecedor_exclui.setBackground(new java.awt.Color(153, 153, 255));
        bt_fornecedor_exclui.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_fornecedor_exclui.setForeground(new java.awt.Color(255, 255, 255));
        bt_fornecedor_exclui.setText("FORNECEDORES");
        bt_fornecedor_exclui.setActionCommand("");
        bt_fornecedor_exclui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_fornecedor_exclui.setBorderPainted(false);
        bt_fornecedor_exclui.setContentAreaFilled(false);
        bt_fornecedor_exclui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_fornecedor_exclui.setOpaque(true);
        bt_fornecedor_exclui.setRequestFocusEnabled(false);
        bt_fornecedor_exclui.setRolloverEnabled(false);

        bt_produto_exclui.setBackground(new java.awt.Color(153, 153, 255));
        bt_produto_exclui.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_produto_exclui.setForeground(new java.awt.Color(255, 255, 255));
        bt_produto_exclui.setText("PRODUTOS");
        bt_produto_exclui.setActionCommand("");
        bt_produto_exclui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_produto_exclui.setBorderPainted(false);
        bt_produto_exclui.setContentAreaFilled(false);
        bt_produto_exclui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_produto_exclui.setOpaque(true);
        bt_produto_exclui.setRequestFocusEnabled(false);
        bt_produto_exclui.setRolloverEnabled(false);

        bt_vs_exclui.setBackground(new java.awt.Color(153, 153, 255));
        bt_vs_exclui.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_vs_exclui.setForeground(new java.awt.Color(255, 255, 255));
        bt_vs_exclui.setText("VENDAS E SERVIÇOS");
        bt_vs_exclui.setActionCommand("");
        bt_vs_exclui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_vs_exclui.setBorderPainted(false);
        bt_vs_exclui.setContentAreaFilled(false);
        bt_vs_exclui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_vs_exclui.setOpaque(true);
        bt_vs_exclui.setRequestFocusEnabled(false);
        bt_vs_exclui.setRolloverEnabled(false);

        bt_conta_exclui.setBackground(new java.awt.Color(153, 153, 255));
        bt_conta_exclui.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_conta_exclui.setForeground(new java.awt.Color(255, 255, 255));
        bt_conta_exclui.setText("CONTAS");
        bt_conta_exclui.setActionCommand("");
        bt_conta_exclui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_conta_exclui.setBorderPainted(false);
        bt_conta_exclui.setContentAreaFilled(false);
        bt_conta_exclui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_conta_exclui.setOpaque(true);
        bt_conta_exclui.setRequestFocusEnabled(false);
        bt_conta_exclui.setRolloverEnabled(false);

        bt_contato_exclui.setBackground(new java.awt.Color(153, 153, 255));
        bt_contato_exclui.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_contato_exclui.setForeground(new java.awt.Color(255, 255, 255));
        bt_contato_exclui.setText("CONTATO");
        bt_contato_exclui.setActionCommand("");
        bt_contato_exclui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_contato_exclui.setBorderPainted(false);
        bt_contato_exclui.setContentAreaFilled(false);
        bt_contato_exclui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_contato_exclui.setOpaque(true);
        bt_contato_exclui.setRequestFocusEnabled(false);
        bt_contato_exclui.setRolloverEnabled(false);

        bt_colaborador_exclui.setBackground(new java.awt.Color(153, 153, 255));
        bt_colaborador_exclui.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_colaborador_exclui.setForeground(new java.awt.Color(255, 255, 255));
        bt_colaborador_exclui.setText("COLABORADORES");
        bt_colaborador_exclui.setActionCommand("");
        bt_colaborador_exclui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_colaborador_exclui.setBorderPainted(false);
        bt_colaborador_exclui.setContentAreaFilled(false);
        bt_colaborador_exclui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_colaborador_exclui.setOpaque(true);
        bt_colaborador_exclui.setRequestFocusEnabled(false);
        bt_colaborador_exclui.setRolloverEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_cliente_exclui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_fornecedor_exclui, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
            .addComponent(bt_produto_exclui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_vs_exclui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_conta_exclui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_contato_exclui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_colaborador_exclui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cliente_exclui, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_fornecedor_exclui, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_produto_exclui, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_vs_exclui, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_conta_exclui, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_contato_exclui, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_colaborador_exclui, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cliente_exclui;
    private javax.swing.JButton bt_colaborador_exclui;
    private javax.swing.JButton bt_conta_exclui;
    private javax.swing.JButton bt_contato_exclui;
    private javax.swing.JButton bt_fornecedor_exclui;
    private javax.swing.JButton bt_produto_exclui;
    private javax.swing.JButton bt_vs_exclui;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
