/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visao.telas;

import br.com.visao.Principal;
import br.com.visao.telas.relatorios.clientes;
import br.com.visao.telas.relatorios.colaboradores;
import br.com.visao.telas.relatorios.contas;
import br.com.visao.telas.relatorios.contatos;
import br.com.visao.telas.relatorios.fornecedores;
import br.com.visao.telas.relatorios.produtos;
import br.com.visao.telas.relatorios.vendas_e_servicos;
import javax.swing.JInternalFrame;

/**
 *
 * @author Rafael Paes Leme
 */
public class Relatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastros
     */
    public Relatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_cliente_relatorio = new javax.swing.JButton();
        bt_fornecedor_relatorio = new javax.swing.JButton();
        bt_produto_relatorio = new javax.swing.JButton();
        bt_vs_relatorio = new javax.swing.JButton();
        bt_conta_relatorio = new javax.swing.JButton();
        bt_contato_relatorio = new javax.swing.JButton();
        bt_colaborador_relatorio = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Opções de Impressão");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bt_cliente_relatorio.setBackground(new java.awt.Color(153, 153, 255));
        bt_cliente_relatorio.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_cliente_relatorio.setForeground(new java.awt.Color(255, 255, 255));
        bt_cliente_relatorio.setText("CLIENTES");
        bt_cliente_relatorio.setActionCommand("");
        bt_cliente_relatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_cliente_relatorio.setBorderPainted(false);
        bt_cliente_relatorio.setContentAreaFilled(false);
        bt_cliente_relatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_cliente_relatorio.setOpaque(true);
        bt_cliente_relatorio.setRequestFocusEnabled(false);
        bt_cliente_relatorio.setRolloverEnabled(false);
        bt_cliente_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cliente_relatorioActionPerformed(evt);
            }
        });

        bt_fornecedor_relatorio.setBackground(new java.awt.Color(153, 153, 255));
        bt_fornecedor_relatorio.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_fornecedor_relatorio.setForeground(new java.awt.Color(255, 255, 255));
        bt_fornecedor_relatorio.setText("FORNECEDORES");
        bt_fornecedor_relatorio.setActionCommand("");
        bt_fornecedor_relatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_fornecedor_relatorio.setBorderPainted(false);
        bt_fornecedor_relatorio.setContentAreaFilled(false);
        bt_fornecedor_relatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_fornecedor_relatorio.setOpaque(true);
        bt_fornecedor_relatorio.setRequestFocusEnabled(false);
        bt_fornecedor_relatorio.setRolloverEnabled(false);
        bt_fornecedor_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fornecedor_relatorioActionPerformed(evt);
            }
        });

        bt_produto_relatorio.setBackground(new java.awt.Color(153, 153, 255));
        bt_produto_relatorio.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_produto_relatorio.setForeground(new java.awt.Color(255, 255, 255));
        bt_produto_relatorio.setText("PRODUTOS");
        bt_produto_relatorio.setActionCommand("");
        bt_produto_relatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_produto_relatorio.setBorderPainted(false);
        bt_produto_relatorio.setContentAreaFilled(false);
        bt_produto_relatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_produto_relatorio.setOpaque(true);
        bt_produto_relatorio.setRequestFocusEnabled(false);
        bt_produto_relatorio.setRolloverEnabled(false);
        bt_produto_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_produto_relatorioActionPerformed(evt);
            }
        });

        bt_vs_relatorio.setBackground(new java.awt.Color(153, 153, 255));
        bt_vs_relatorio.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_vs_relatorio.setForeground(new java.awt.Color(255, 255, 255));
        bt_vs_relatorio.setText("VENDAS E SERVIÇOS");
        bt_vs_relatorio.setActionCommand("");
        bt_vs_relatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_vs_relatorio.setBorderPainted(false);
        bt_vs_relatorio.setContentAreaFilled(false);
        bt_vs_relatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_vs_relatorio.setOpaque(true);
        bt_vs_relatorio.setRequestFocusEnabled(false);
        bt_vs_relatorio.setRolloverEnabled(false);
        bt_vs_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_vs_relatorioActionPerformed(evt);
            }
        });

        bt_conta_relatorio.setBackground(new java.awt.Color(153, 153, 255));
        bt_conta_relatorio.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_conta_relatorio.setForeground(new java.awt.Color(255, 255, 255));
        bt_conta_relatorio.setText("CONTAS");
        bt_conta_relatorio.setActionCommand("");
        bt_conta_relatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_conta_relatorio.setBorderPainted(false);
        bt_conta_relatorio.setContentAreaFilled(false);
        bt_conta_relatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_conta_relatorio.setOpaque(true);
        bt_conta_relatorio.setRequestFocusEnabled(false);
        bt_conta_relatorio.setRolloverEnabled(false);
        bt_conta_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_conta_relatorioActionPerformed(evt);
            }
        });

        bt_contato_relatorio.setBackground(new java.awt.Color(153, 153, 255));
        bt_contato_relatorio.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_contato_relatorio.setForeground(new java.awt.Color(255, 255, 255));
        bt_contato_relatorio.setText("CONTATO");
        bt_contato_relatorio.setActionCommand("");
        bt_contato_relatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_contato_relatorio.setBorderPainted(false);
        bt_contato_relatorio.setContentAreaFilled(false);
        bt_contato_relatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_contato_relatorio.setOpaque(true);
        bt_contato_relatorio.setRequestFocusEnabled(false);
        bt_contato_relatorio.setRolloverEnabled(false);
        bt_contato_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_contato_relatorioActionPerformed(evt);
            }
        });

        bt_colaborador_relatorio.setBackground(new java.awt.Color(153, 153, 255));
        bt_colaborador_relatorio.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        bt_colaborador_relatorio.setForeground(new java.awt.Color(255, 255, 255));
        bt_colaborador_relatorio.setText("COLABORADORES");
        bt_colaborador_relatorio.setActionCommand("");
        bt_colaborador_relatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        bt_colaborador_relatorio.setBorderPainted(false);
        bt_colaborador_relatorio.setContentAreaFilled(false);
        bt_colaborador_relatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_colaborador_relatorio.setOpaque(true);
        bt_colaborador_relatorio.setRequestFocusEnabled(false);
        bt_colaborador_relatorio.setRolloverEnabled(false);
        bt_colaborador_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_colaborador_relatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_cliente_relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_fornecedor_relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
            .addComponent(bt_produto_relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_vs_relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_conta_relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_contato_relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_colaborador_relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cliente_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_fornecedor_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_produto_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_vs_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_conta_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_contato_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_colaborador_relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cliente_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cliente_relatorioActionPerformed

        clientes clie = new clientes();
        chamarTelas(clie);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bt_cliente_relatorioActionPerformed

    private void bt_fornecedor_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fornecedor_relatorioActionPerformed

        fornecedores forn = new fornecedores();
        chamarTelas(forn);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bt_fornecedor_relatorioActionPerformed

    private void bt_produto_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_produto_relatorioActionPerformed

        produtos prd = new produtos();
        chamarTelas(prd);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bt_produto_relatorioActionPerformed

    private void bt_vs_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_vs_relatorioActionPerformed

        vendas_e_servicos vs = new vendas_e_servicos();
        chamarTelas(vs);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bt_vs_relatorioActionPerformed

    private void bt_conta_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_conta_relatorioActionPerformed

        contas c = new contas();
        chamarTelas(c);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bt_conta_relatorioActionPerformed

    private void bt_contato_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_contato_relatorioActionPerformed

        contatos ct = new contatos();
        chamarTelas(ct);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bt_contato_relatorioActionPerformed

    private void bt_colaborador_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_colaborador_relatorioActionPerformed

        colaboradores clb = new colaboradores();
        chamarTelas(clb);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bt_colaborador_relatorioActionPerformed

    
        private void chamarTelas(JInternalFrame p) {

        Principal.getPainel().add(p);
        p.setVisible(true);

        int x = (Principal.getPainel().getWidth() / 2) - (p.getWidth() / 2);
        int y = (Principal.getPainel().getHeight() / 2) - (p.getHeight() / 2);
        p.setVisible(true);
        p.setLocation(x, y);
        p.toFront();
        p.show();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cliente_relatorio;
    private javax.swing.JButton bt_colaborador_relatorio;
    private javax.swing.JButton bt_conta_relatorio;
    private javax.swing.JButton bt_contato_relatorio;
    private javax.swing.JButton bt_fornecedor_relatorio;
    private javax.swing.JButton bt_produto_relatorio;
    private javax.swing.JButton bt_vs_relatorio;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
