/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visao.telas;

/**
 *
 * @author Rafael Paes Leme
 */
public class Temas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Temas
     */
    public Temas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        bt_azul = new javax.swing.JButton();
        bt_preto = new javax.swing.JButton();
        bt_amarelo = new javax.swing.JButton();
        bt_verde = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_dialogo = new javax.swing.JTextArea();
        bt_padrao = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Escolha um tema para Area De Trabalho");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        bt_azul.setBackground(new java.awt.Color(0, 102, 153));
        bt_azul.setFont(new java.awt.Font("Khmer UI", 0, 11)); // NOI18N
        bt_azul.setText("Azul");
        bt_azul.setBorderPainted(false);
        bt_azul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bt_preto.setBackground(new java.awt.Color(51, 51, 51));
        bt_preto.setFont(new java.awt.Font("Khmer UI", 0, 11)); // NOI18N
        bt_preto.setForeground(new java.awt.Color(255, 255, 255));
        bt_preto.setText("Preto");
        bt_preto.setBorderPainted(false);
        bt_preto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bt_amarelo.setBackground(new java.awt.Color(204, 204, 0));
        bt_amarelo.setFont(new java.awt.Font("Khmer UI", 0, 11)); // NOI18N
        bt_amarelo.setText("Amarelo");
        bt_amarelo.setBorderPainted(false);
        bt_amarelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bt_verde.setBackground(new java.awt.Color(0, 204, 153));
        bt_verde.setFont(new java.awt.Font("Khmer UI", 0, 11)); // NOI18N
        bt_verde.setText("Verde");
        bt_verde.setBorderPainted(false);
        bt_verde.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel20.setFont(new java.awt.Font("Khmer UI", 0, 11)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Escolha um Tema");

        txt_dialogo.setEditable(false);
        txt_dialogo.setColumns(20);
        txt_dialogo.setFont(new java.awt.Font("Khmer UI", 0, 13)); // NOI18N
        txt_dialogo.setForeground(new java.awt.Color(204, 0, 0));
        txt_dialogo.setLineWrap(true);
        txt_dialogo.setRows(5);
        txt_dialogo.setText("Obs.: As Escolhas de tema para esta versão do sistema é temporaria. (Sempre sera exibida a escolha de tema padrão).");
        jScrollPane1.setViewportView(txt_dialogo);

        bt_padrao.setBackground(new java.awt.Color(204, 204, 204));
        bt_padrao.setFont(new java.awt.Font("Khmer UI", 0, 11)); // NOI18N
        bt_padrao.setText("PADRÃO");
        bt_padrao.setBorderPainted(false);
        bt_padrao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_amarelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_verde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_azul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)))
                    .addComponent(bt_padrao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_azul)
                    .addComponent(jLabel20))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(bt_preto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_amarelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_verde))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_padrao)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 504, 226);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_amarelo;
    private javax.swing.JButton bt_azul;
    private javax.swing.JButton bt_padrao;
    private javax.swing.JButton bt_preto;
    private javax.swing.JButton bt_verde;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_dialogo;
    // End of variables declaration//GEN-END:variables
}
